In [13]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [14]:
df=pd.read_csv(r'D:\New folder\iris.data/Iris.csv')

In [15]:
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [17]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [18]:
X=df.iloc[:,0:4]

In [19]:
X

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0      1            5.1           3.5            1.4
1      2            4.9           3.0            1.4
2      3            4.7           3.2            1.3
3      4            4.6           3.1            1.5
4      5            5.0           3.6            1.4
..   ...            ...           ...            ...
145  146            6.7           3.0            5.2
146  147            6.3           2.5            5.0
147  148            6.5           3.0            5.2
148  149            6.2           3.4            5.4
149  150            5.9           3.0            5.1

[150 rows x 4 columns]

In [20]:
y=df.iloc[:,-1]

In [21]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [22]:
X=df.drop(['Id','Species'],axis=1)

In [23]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [24]:
from sklearn.preprocessing import LabelEncoder`

SyntaxError: invalid syntax (2582622206.py, line 1)

In [25]:
le=LabelEncoder()

NameError: name 'LabelEncoder' is not defined

In [ ]:
#encoding ------> label encoding
le.fit_transform(y)

In [ ]:
y

In [26]:
# Feature scalling.....
# Standard scalling
from sklearn.preprocessing import StandardScaler

In [27]:
ss=StandardScaler()

In [28]:
ss = StandardScaler()


In [29]:
X.head(4)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2

In [30]:
Scaled_fit=ss.transform(X)

NotFittedError: This StandardScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [31]:
Scaled_fit

NameError: name 'Scaled_fit' is not defined

In [32]:
df_feat=pd.DataFrame(Scaled_fit,columns=X.columns)

NameError: name 'Scaled_fit' is not defined

In [33]:
df_feat.head(4)

NameError: name 'df_feat' is not defined

In [34]:
df_feat.describe()

NameError: name 'df_feat' is not defined

In [35]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
#X_train,X_test,y_train,y_test = train_test_split(X,y test_size=0.3,random_state=101)

In [38]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state=101)

In [39]:
#  import KNN
from sklearn.neighbors import KNeighborsClassifier

In [40]:
knn = KNeighborsClassifier(n_neighbors=5)

In [41]:
knn.fit(X_test,y_test)

KNeighborsClassifier()

In [42]:
pred = knn.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix,classification_report

In [44]:
print(confusion_matrix(y_test,pred))

[[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]


In [45]:
print(classification_report(y_test,pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.95      0.97        20
 Iris-virginica       0.92      1.00      0.96        12

       accuracy                           0.98        45
      macro avg       0.97      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45

